### ISSUE TITLE
General issues with the concepts page

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#11]
I put this as a reminder as I provided my comments as a pull request and review comments here:
#10

**Comment by sharronrush** [comment]
In addition, the Concepts page has no mention of the players even though that is part of this resource.  It should be introduced here as well.

**Comment by sharronrush** [comment]
Suggested rewrite of a sentence on Concepts page, suggested for brevity and clarity:

CURRENT: In the same way that low-quality, incomplete audio is unacceptable to hearing viewers, captions that do not accurately reflect the audio, or contain spelling and grammatical errors, are unacceptable to deaf and hard-of-hearing viewers. 

SUGGESTION: Hearing viewers find low-quality, incomplete audio content unacceptable. Similarly, captions that are inaccurate or contain spelling and grammatical errors are unacceptable to deaf and hard-of-hearing viewers.

**Comment by gfreedncam** [comment]
edited.
