### ISSUE TITLE
[Captions - p1] Broken link

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-media-intro#12]
First paragraph, link text  "recognized to benefit many audiences" 
Links to:   https://w3c.github.io/wai-tutorials/accessible-media/production-captions/concepts.html#cc+ad_purpose 
Result: returns 404

**Comment by yatil** [comment]
That should be index.html, and I have changed this in #15.

**Comment by gfreedncam** [comment]
text was edited to remove this link.
