### ISSUE TITLE
[Captions - p1] Redundant use of "always"

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-media-intro#14]
CURRENT: Captions always reflect dialog and narration, and are always written in the same language as the audio...

SUGGESTED: Captions are a text display of dialog and narration and are written in the same language as the audio...

RATIONALE: Redundant comma and the word 'always'  is unnecessary since definitions are by their nature a statement of a persistent fact that needs no emphasis.

In the same paragraph, the use of "They" in the sentence "They also contain..." is ambiguous. Does 'They' refer to captions or subtitles?

**Comment by gfreedncam** [comment]
changed.
