### ISSUE TITLE
[Captions] Examples for caption types

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#18]
The examples for caption types (pop-on, roll-up and paint-on) look all different and are also very small and a bit noisy. 

* Some of the examples are not on a w3.org server – do we have the rights to use them? 
* I think it would be good to have more schematic short videos that show the behavior of the caption types.

**Comment by gfreedncam** [comment]
NCAM can host these clips, but they cannot be put on W3C servers.  i agree that new/other clips would be useful, but that requires funding...
