### ISSUE TITLE
[Captions] Basic Workflow feedback

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#19]
> 1.  **Enter caption text into the editor**
>     Transcribe the audio directly into the caption editor or, if available, import a transcript.

Maybe link to the transcript page here.

> 2.  **Edit and break text into captions**
>     Edit for proper spelling and grammar; divide the text into caption blocks.

How big are such blocks? How many words should be on a line? Is there any advice on this?

> 3.  **Time the captions**
>     Assign a timecode to each caption that indicates when it will appear or disappear from the screen.

How much time should words be on the screen? What if there is too much text to be displayed during that time? (Hello, I’m German!) Can sentences be contracted if they can’t be reproduced word for word?

> 4.  **Review the captions**
>     Watch the captioned video carefully and eliminate any errors. Accuracy is paramount: misspelled or poorly edited and timed captions will only make it harder for viewers to follow what is happening on-screen.
> 5.  **Export a caption file**
>     Export the captions in the target format. See [caption formats and examples](formats.html) for more information.

**Comment by jespulido** [comment]
> How big are such blocks? How many words should be on a line? Is there any advice on this?

In our practice, our general rule of thumb -- and I'm sure there are other approaches -- but to save headaches and facilitate conversion from one format to another, and to prevent hiccups when working with stenographers, we limit each block to two lines, with a maximum of 32 characters per line. It's based on the "608" standard, which is now legacy. https://en.wikipedia.org/wiki/EIA-608

**Comment by jespulido** [comment]
It originates from this standard: https://en.wikipedia.org/wiki/EIA-608

**Comment by jespulido** [comment]
> How much time should words be on the screen? What if there is too much text to be displayed during that time? (Hello, I’m German!) 

The DCMP's guidance says

> Captions should have a minimum duration of 40 frames (1 second and 10 frames).
Captions should have a maximum duration of 6 seconds. (Background music notation is an exception to this guideline).

http://www.captioningkey.org/text.html

> Can sentences be contracted if they can’t be reproduced word for word?

Hollywood productions will often paraphrase what is actually spoken. In the educational setting, we would never do that. In the educational setting, we would require the captions to be verbatim of what's said (plus sound effects, etc.)

**Comment by gfreedncam** [comment]
changed the transcript reference to this:

===
Transcribe the audio directly into the caption editor or, if available, import a transcript that has been prepared ahead of time using a text editor.
===

your other points are all valid, but they fall into the topic of caption styles and so i think are out of scope for this tutorial.  most of these questions are addressed in the DCMP's guidelines, though.
