### ISSUE TITLE
[Captions] Basic Workflow example screen shot

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#20]
The image has empty end timings. I think that means that the caption is hidden when the next one is displayed, but we should make that explicit.

**Comment by gfreedncam** [comment]
agree.  changed to this:

Below is an image of a caption editor showing how captions have been
formatted and timestamped. Each caption is assigned a start/display time. In this editor, captions that are not assigned end/erase times will simply be replaced when the next caption displays.

side note: even though this particular caption editor does not require authors to assign an end/erase time to each caption, those end times are automatically calculated and assigned when the caption file is exported.
