### ISSUE TITLE
[Caption] Resources for writing quality captions

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#23]
I think we should have (some) of this information in the document, especially that the links are pointing to non-W3C pages where we can’t guarantee that the content will not change.

**Comment by gfreedncam** [comment]
not sure how we can avoid external references here, though.  ?

**Comment by gfreedncam** [comment]
while i don't disagree, i think  including stylistic information would be out of scope for this tutorial.  the DCMP guidelines really are the best resource currently available; i don't see how we can avoid linking to them.
