### ISSUE TITLE
General neglect of deaf-blind and transcripts

### ISSUE THREAD

**Issue by steverep** [w3c/wai-media-intro#24]
Skimming over this tutorial, I thought it was a great first draft, but I was surprised not to see transcripts in the main title along with captions and audio descriptions, and deaf-blind individuals are not even mentioned on the main page.  There is only a note at the bottom which I'm not sure I even understand:

> In some cases, captions and descriptions may be the only means by which users can access any information at all from video or audio clips.

I assume this is supposed to refer to folks with deaf-blindness?  If so, I don't think this is an accurate statement since the captions and audio descriptions would only be accessible if they were provided in a transcript format.  In general, the needs and methods of deaf-blind users are too neglected.

Here's a quick first cut of issues I think need to be addressed:
- [ ] Include deaf-blind users in the list with other disabilities and emphasize how their only avenue to accessible media may be reading a transcript using Braille.  At a minimum, this needs to be included on the main page and the page on creating transcripts in the uses listed at the top.
- [ ] Throughout the tutorial, it is either implied or directly stated that equivalent transcripts are simply created by writing down the audio track with speakers and sound effects, i.e. just writing down the captions.  It's not an equivalent alternative for deaf-blind users, or any other user consuming the transcript only, unless it also includes all information in the audio description track.
- [ ] The page on "playing media" needs to be altered to something like "consuming media" or "using media", and methods for providing transcripts needs to be added, including players that may generate them automatically.  Also, the heading structure here doesn't make much sense to me since customizing captions is not included in the captions section.

Thanks for your work on this so far and your consideration in addressing these issues.

**Comment by gfreedncam** [comment]
good points; added information pertinent pages about the importance of transcripts to users who are deaf-blind.  would prefer to leave the text "playing media" as is, however.
