### ISSUE TITLE
Minor link and wording adjustments

### ISSUE THREAD

**Issue by jake-abma** [w3c/wai-media-intro#25]
**Accessible Media Concepts**

> Subtitles: A text version of a program's audio track, fully synchronized with the audio and translated into another language.

Should be: …and most frequently used to translate into another language…

> …or words can selected by the user 

Add “be”: …or words can be... selected by the user 

> In the same way that low-quality, incomplete audio is unacceptable to hearing viewers, captions that do not accurately reflect the audio, or contain spelling and grammatical errors, are unacceptable to deaf and hard-of-hearing viewers.

The whole sentence should be rewritten as it is a difficult one.

> captions and descriptions have benefits

Be consistent: captions and audio descriptions have benefits

**Production options for captions**

> https://w3c.github.io/wai-tutorials/accessible-media/production-captions/concepts.html#cc+ad_purpose

Link doesn’t work

> subtitles, on the other hand, are a translation of the audio into another language

This is not definitely so, better to say something like: "subtitles are most frequently used for another language..."

> See the discussion about automatic captions for more information.

There’s no discussion, need two or more parties for a discussion...

**Caption formats and examples**

Link doesn’t work:  “and text-based audio descriptions”

**Subtitle concepts and examples**

> Differences between subtitles and captions => “Subtitles, Translation of the audio” 

Also here it should be: “Subtitles, translations, as well as same language, of the audio”

**Transcript Concepts and Examples**

> Users can quickly scan a transcript to learn about a video's subject matter prior to watching the video.

Also add audio here “Users can quickly scan a transcript to learn about a video or audio file subject matter prior to watching or hearing the audio or video.

> or words can selected by the user

Also add “be” here: “or words can be selected by the user

**Comment by gfreedncam** [comment]
corrected typos and broken links; addressed most other items but will leave to references to subtitles as they are.
