### ISSUE TITLE
[auto-captions] vs. [caption production] Censoring

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#30]
[caption production] page says:

* 100% accuracy 
* Do not censor

[auto-captions] says:

* “poor quality captions often contain […] occasional obscenities (swears, for example)”

**Question:** Is anything that is not 100% accurate considered inaccessible? What if I’m legally required to censor material? What if the video’s audio itself is censored (bleeped)? While one page says don’t censor, the other one makes you aware that there might be some things that you’d want to edit. 

This is confusing.

**Comment by gfreedncam** [comment]
I am of the mind that pre-produced (i.e., pre-recorded) captions should be 100% accurate.  Less-than-completely-accurate captions do not necessarily equate to inaccessible media (some deaf or hard-of-hearing viewers might disagree), but if the video exists in a pre-produced state, and care has been taken to produce high-quality audio, the same care should be given to the captions.  

"Do not censor" refers to the practice of editing "objectionable" language from the captions even though that language remains in the audio track.  Changed the reference to this:

Do not censor: captions should reflect the words that are spoken in the audio track.  If objectionable words are used in the audio, the captions should show those words.  If the audio is edited to obscure a specific word or phrase (e.g., "bleeped" audio), the captions should reflect the fact that a word or phrase has been obscured.
