### ISSUE TITLE
[audio description] Examples

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#37]
On several occasions on the page (and other pages), examples are mentioned and then linked to externally.

As those examples can vanish at any time, it would be good to have some example inline that is then reliably available for the reader.

Some confusing examples of this:

> Other non-markup-based methods have been experimented with, such as creating an open-described video with a video track that appears to freeze while a separate open-description track plays. See an [example of a video with open extended audio descriptions](https://mass.pbslearningmedia.org/resource/tdc02.sci.life.reg.deathvall/teri-and-jairus-biome-buddies/na/) (created using a non-markup method). 

The link goes to a confusing third party site where I’m confused about what to do and how to find the example.

> Also, read [one method for creating videos with extended open audio descriptions (see chapter 4.9)](http://ncam.wgbh.org/file_download/103).

This link immediately downloads a PDF (!sic) to user’s computer. The PDF has no chapter bookmarks (on MacOS). The URL does not look particularly persistent.

**Comment by gfreedncam** [comment]
added instructions for playing the extended-AD example.  the document referenced above is only available as a PDF, unfortunately.  there isn't much other documentation available for creating extended descriptions.  i know that the document link is, in fact, persistent, but if linking to a PDF is problematic i can remove the reference.
