### ISSUE TITLE
[audio descriptions] Resources for writing descriptions

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#38]
> ## Resources for writing descriptions
> 
> The importance of presenting users with high-quality, accurate descriptions cannot be overemphasized. Use the guidelines below to help create descriptions that are informative and useful.
> 
> -  [<abbr title="Described and Captioned Media Program">DCMP</abbr> Description Key](http://www.descriptionkey.org/how_to_describe.html)
> -  [<abbr title="Described and Captioned Media Program">DCMP</abbr> Description Tip Sheet](https://www.dcmp.org/ai/227/)
> -  [Accessible Multimedia whitepaper](http://diagramcenter.org/research.html#multimedia)

Should this information not be inlined and part of the developer’s intro? 

The last link links to a website where you have to download a Word (!sic) document. It is unclear who has written the whitepaper. It has a lot of information that is similar to this developer’s intro (maybe some that is contradictory) it seems from a quick skim.

**Comment by gfreedncam** [comment]
agree; deleted reference to the whitepaper.
