### ISSUE TITLE
[Accessible Media Concepts] Subtitles Definition

### ISSUE THREAD

**Issue by jespulido** [w3c/wai-media-intro#44]
CURRENT: Subtitles: A text version of a program's audio track, fully synchronized with the audio and translated into another language.

SUGGESTED: Subtitles: A text version of a program's audio track, fully synchronized with the audio and translated from another language.

RATIONALE: I know this is a minor edit -- and I apologize if this has already been discussed -- but I think it makes more sense to say "from" instead of "into," since the user will be reading the subtitles in their native language.

**Comment by gfreedncam** [comment]
would prefer to leave as is.  the program-audio track is the original source language; subtitles are used to translate that source to a different language.  the viewer may not be reading subtitles in his or her native language:  e.g., if i am an english speaker and am studying italian, perhaps i simply want to read the italian subtitles (while listening to the english program audio) to help my language skills.
