### ISSUE TITLE
[transcripts] linking to external pages

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-media-intro#45]
I just have a concern about linking to external pages like NYTimes. What if the content changes?  can we request access to pull these resources into an internal page?

Transcripts can be presented to users in a number of ways:

linking to a separate document or Web page;
integrated into the same Web page as the video;
as an interactive transcript that can be used as a method to navigate through a video clip.

**Comment by shawna-slh** [comment]
+1 to concern for linking to external pages

**Comment by gfreedncam** [comment]
agree; changed the example from NYT to one from the WAI Accessibility Perspectives page.
