### ISSUE TITLE
[playing] Wording/sentence structure

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-media-intro#46]
If you're going to "note" something - call it out a little better, either by bolding it or pulling it out of the paragraph.

 Note that in any player on any operating system, the settings chosen by the user will override any author-specified styling characteristics (see further comments about author styling of captions).

**Comment by shawna-slh** [comment]
Appreciate the idea.

I think in this case it's just a use of speech, and I don't think we want added visual clutter to call it out more. However, I'm not looking at it in context right now - so maybe it does warrant call out. :)

**Comment by jespulido** [comment]
I think this is an important point. Maybe move the phrase "Note that" could be moved to the very beginning of that section?

**Comment by yatil** [comment]
I had a look and put the note format in where it did fit and was not only used as a figure of speech. Notes are basically de-emphasized paragraphs.

**Comment by gfreedncam** [comment]
will leave as is.
