### ISSUE TITLE
Concepts - why is this important

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-media-intro#49]
Might consider adding:

There is evidence that captioning increases engagement for all viewers.

**Comment by shawna-slh** [comment]
Transcripts, too http://www.uiaccess.com/transcripts/transcripts_on_the_web.html#benes

**Comment by gfreedncam** [comment]
agree.  will alter the first bullet:
•	Both captions and descriptions can be used to help all viewers, especially those with cognitive disabilities, engage more directly with media, helping to focus attention or to provide comprehension support.
