### ISSUE TITLE
Caption workflow - maybe explain reason for export

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-media-intro#51]
Readers might wonder the purpose of step 5: exporting a caption. Perhaps an explanation of why you might export a caption fire: for creating a transcript or to sync with a different video format for example.

Text excerpt: 
5. Export a caption file
Export the captions in the target format. See caption formats and examples for more information.

**Comment by gfreedncam** [comment]
agree.  change to "Export the captions in the target format so they can be synchronized with the media, or provided as a transcript. See caption formats and examples for more information.
