### ISSUE TITLE
FYI: subtitles vs. captions

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#52]
* BBC is using a [s] button to show “subtitles”: http://www.bbc.co.uk/programmes/p05007nb (might autoplay)
* TED is also using the term “subtitles” instead of captions: https://www.ted.com/talks/tim_berners_lee_a_magna_carta_for_the_web?language=en (I guess here it is to not having to distinguish between captions for English and subtitles for other languages.)

**Comment by gfreedncam** [comment]
i don't think this tutorial can or should referee the decades-old international confusion between these two terms.  i vote to  just stick with the north-american definition and WCAG glossary term: https://www.w3.org/TR/2006/WD-WCAG20-20060427/appendixA.html .
