### ISSUE TITLE
Closing </p> is visible

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-media-intro#7]
https://w3c.github.io/wai-tutorials/accessible-media/production-audio-description

Under Extended Descriptions

See an example of a video with open extended audio descriptions (created using a non-markup method). Also, read one method for creating videos with extended open audio descriptions (see chapter 4.9).**</p>**

**Comment by yatil** [comment]
+1 That was my bad. I’ll make sure it is not there when we publish.

**Comment by gfreedncam** [comment]
fixed (i think?)
