### ISSUE TITLE
Two sections seem to contradict each other

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-media-intro#8]
See:   https://w3c.github.io/wai-tutorials/accessible-media/production-captions/
Under Caption Quality
•	Do not censor: the captions should always accurately represent what is spoken.

See: https://w3c.github.io/wai-tutorials/accessible-media/automatically-generated-captions/
Under The basics of Automated Captions
However, the accuracy of these captions is frequently quite low and results in poor-quality captions that often contain…
•	occasional obscenities (swears, for example).

This item is confusing. If swears are a part of the video shouldn’t they be included. Or is this item implying something different.

**Comment by yatil** [comment]
+1 I found that as well

**Comment by gfreedncam** [comment]
corrected; addressed in a separate issue.
