### ISSUE TITLE
General Question about Implementing Audio Descriptions

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-media-intro#9]
https://w3c.github.io/wai-tutorials/accessible-media/production-audio-description/

**Under Pre-Produced Audio Descriptions**
**See an example of a described video**, and be sure to select the “Enable audio description” button located just below the player to turn on the descriptions.
In this example, the audio described video is 1:17 minutes long and the video with audio descriptions disabled is 0:47 minutes long. This method is different than the extended descriptions approach that pauses the video while the descriptions are being read.

**Under Extended Descriptions**
I also read the paragraph about extended descriptions and viewed the Zoom video.

After reading this page, I understand that there are multiple ways to implement audio descriptions, however, after reading this section I still felt that I did not have enough information on how to incorporate audio descriptions and sync the added content with the presentation.

There is some discussion about each approach but I think that a more in depth discussion could be helpful.

**Comment by gfreedncam** [comment]
actually, the example at https://mass.pbslearningmedia.org/resource/tdc02.sci.life.reg.deathvall/teri-and-jairus-biome-buddies/na/ *does* demonstrate extended audio descriptions, thus the difference in timing between the described/non-described version.

**Comment by gfreedncam** [comment]
re incorporating AD tracks into a presentation: beyond the basic details that are included in this tutorial, i think what would be most useful would be a guide to editing the descriptions into the main audio track itself.  this is beyond the scope of the tutorial, however.
